name: Workflow para Commits

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout do código
        uses: actions/checkout@v3


      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Instalar dependências
        run: npm install

      # Rodar os testes
      - name: Rodar os testes
        run: npm test
